main: p1xel.minecraft.bukkit.MyVillager
name: MyVillager
version: ${project.version}
api-version: 1.13
folia-supported: true
commands:
  myvillager:
    aliases: [mv, myv]

permissions:
  myvillager.claim:
    default: true
  myvillager.lock:
    default: true
  myvillager.info:
    default: true
  myvillager.info.other:
    default: true
  myvillager.list:
    default: true
  myvillager.group:
    default: true
  myvillager.group.create:
    default: true
  myvillager.group.delete:
    default: true
  myvillager.group.info:
    default: true
  myvillager.group.set:
    default: true
  myvillager.group.unset:
    default: true
  myvillager.group.set.player:
    default: true
  myvillager.group.unset.player:
    default: true
  myvillager.group.set.villager:
    default: true
  myvillager.group.unset.villager:
    default: true
  myvillager.admin:
    default: op
  myvillager.admin.lock:
    default: op
  myvillager.admin.remove:
    default: op
  myvillager.reload:
    default: op